package com.pragma.order_service.domain.exception;

public enum DomainErrorCode {
    VALIDATION_ERROR,
    DUPLICATE_NIT,
    DUPLICATE_NAME,
    OWNER_NOT_FOUND,
    RESTAURANT_NOT_FOUND,
    DISH_NOT_FOUND,
    INVALID_OWNER_ROLE,
    INVALID_OWNER_RESTAURANT,
    INVALID_TOKEN,
    ACCESS_DENIED,
    ACTIVE_ORDER_EXISTS,
    INVALID_ORDER_RESTAURANT,
    EMPLOYEE_RESTAURANT_NOT_FOUND,
    INTERNAL_ERROR
}
